site_name: DjangoDIY 
theme:
  name: material
  icon:
    logo: simple/nucleo
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.expand
    - navigation.path
    - content.code.copy
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: #7b42f5
      accent: deep orange
nav: 
  - Philosophy: index.md
  - Our Apps:
    - DIYblog app: diyblog/blog.md
    - DIYTours app: DiyTours/overview.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences